name: build

on: [push, pull_request]

jobs:
    mac:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v1
        - name: macOS
          run: |
            brew install qt5 mosquitto libuv sdl2 libpq sdl2_mixer
            mkdir build
            cd build
            cmake ..
            make -j 2
            ctest -V -C Debug -R tests-animation$
            ctest -V -C Debug -R tests-backend$
            ctest -V -C Debug -R tests-computeshadertool$
            ctest -V -C Debug -R tests-cooldown$
            ctest -V -C Debug -R tests-core$
            ctest -V -C Debug -R tests-eventmgr$
            ctest -V -C Debug -R tests-math$
            ctest -V -C Debug -R tests-persistence$
            ctest -V -C Debug -R tests-poi$
            ctest -V -C Debug -R tests-shadertool$
            ctest -V -C Debug -R tests-stock$
            ctest -V -C Debug -R tests-testtraze$
            ctest -V -C Debug -R tests-util$
            ctest -V -C Debug -R tests-uuid$
            ctest -V -C Debug -R tests-video$
            ctest -V -C Debug -R tests-voxedit-util$
            ctest -V -C Debug -R tests-voxel$
            ctest -V -C Debug -R tests-voxelformat$
            ctest -V -C Debug -R tests-voxelgenerator$
            ctest -V -C Debug -R tests-voxelrender$
            ctest -V -C Debug -R tests-voxelutil$
            ctest -V -C Debug -R tests-voxelworld$
            ctest -V -C Debug -R tests-voxelworldrender$
    linux:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Linux
          run: |
            sudo apt-get update
            sudo apt-get install lua5.3 liblua5.3-dev libsdl2-dev postgresql-server-dev-10 libpq-dev libenet-dev qt5-default qttools5-dev qttools5-dev-tools opencl-c-headers wayland-protocols pkg-config uuid-dev
            mkdir build
            cd build
            cmake ..
            make -j 2
            ctest -V -C Debug -R tests-ai$
            ctest -V -C Debug -R tests-animation$
            ctest -V -C Debug -R tests-backend$
            ctest -V -C Debug -R tests-computeshadertool$
            ctest -V -C Debug -R tests-cooldown$
            ctest -V -C Debug -R tests-core$
            ctest -V -C Debug -R tests-eventmgr$
            ctest -V -C Debug -R tests-math$
            ctest -V -C Debug -R tests-noise$
            ctest -V -C Debug -R tests-persistence$
            ctest -V -C Debug -R tests-poi$
            ctest -V -C Debug -R tests-shadertool$
            ctest -V -C Debug -R tests-stock$
            ctest -V -C Debug -R tests-testtraze$
            ctest -V -C Debug -R tests-util$
            ctest -V -C Debug -R tests-uuid$
            ctest -V -C Debug -R tests-video$
            ctest -V -C Debug -R tests-voxedit-util$
            ctest -V -C Debug -R tests-voxel$
            ctest -V -C Debug -R tests-voxelformat$
            ctest -V -C Debug -R tests-voxelgenerator$
            ctest -V -C Debug -R tests-voxelrender$
            ctest -V -C Debug -R tests-voxelutil$
            ctest -V -C Debug -R tests-voxelworld$
            ctest -V -C Debug -R tests-voxelworldrender$
    windows:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v1
        - name: Windows
          run: |
            set VCPKG_DEFAULT_TRIPLET=x64-windows
            set VCPKG_BUILD_TYPE=release
            vcpkg install libpq
            mkdir build
            cd build
            cmake .. -DRCON=OFF -DCMAKE_BUILD_TYPE=Release -DDISABLE_UNITY=OFF
            cmake --build .
            cmake --install . --component voxedit --prefix voxedit-install
            cmake --install . --component mapview --prefix mapview-install
            cmake --install . --component voxconvert --prefix voxconvert-install
            ctest -V -C Debug -R tests-ai$
            ctest -V -C Debug -R tests-animation$
            ctest -V -C Debug -R tests-backend$
            ctest -V -C Debug -R tests-computeshadertool$
            ctest -V -C Debug -R tests-cooldown$
            ctest -V -C Debug -R tests-core$
            ctest -V -C Debug -R tests-eventmgr$
            ctest -V -C Debug -R tests-math$
            ctest -V -C Debug -R tests-noise$
            ctest -V -C Debug -R tests-persistence$
            ctest -V -C Debug -R tests-poi$
            ctest -V -C Debug -R tests-shadertool$
            ctest -V -C Debug -R tests-stock$
            ctest -V -C Debug -R tests-util$
            ctest -V -C Debug -R tests-uuid$
            ctest -V -C Debug -R tests-video$
            ctest -V -C Debug -R tests-voxedit-util$
            ctest -V -C Debug -R tests-voxel$
            ctest -V -C Debug -R tests-voxelformat$
            ctest -V -C Debug -R tests-voxelgenerator$
            ctest -V -C Debug -R tests-voxelrender$
            ctest -V -C Debug -R tests-voxelutil$
            ctest -V -C Debug -R tests-voxelworld$
        - name: Upload the voxedit artifacts
          uses: actions/upload-artifact@v2
          with:
            name: voxedit
            path: build/voxedit-install/
        - name: Upload the mapview artifacts
          uses: actions/upload-artifact@v2
          with:
            name: mapview
            path: build/mapview-install/
        - name: Upload the voxconvert artifacts
          uses: actions/upload-artifact@v2
          with:
            name: voxconvert
            path: build/voxconvert-install/
