name: Manual

on:
  workflow_dispatch:

jobs:
    packages:
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v1

        - name: Setup
          run: |
            sudo apt-get update
            sudo apt-get install cmake debhelper devscripts build-essential lintian libsdl2-dev libuv1-dev libsdl2-mixer-dev postgresql-server-dev-12 libpq-dev libenet-dev opencl-c-headers wayland-protocols pkg-config uuid-dev

        - name: Ubuntu
          run: |
            debuild -b -ui -uc -us
            mv ../*.deb .

        - name: Upload the ubuntu artifacts
          uses: actions/upload-artifact@v2
          with:
            name: debian
            path: vengi*.deb

        - name: Upload the ubuntu release artifacts
          if: startsWith(github.ref, 'refs/tags/')
          uses: Roang-zero1/github-upload-release-artifacts-action@master
          with:
            args: vengi*.deb
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    mingw64:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install mingw-w64

        - name: Mingw64
          run: |
            mkdir build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release
            cmake --build .
